"""initial schema

Revision ID: 964d70a06320
Revises:
Create Date: 2026-10-06 14:53:06.751453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964d70a06320'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'name', name='uq_knowledge_nodes_course_name')
    )
    op.create_index('ix_knowledge_nodes_course_id', 'knowledge_nodes', ['course_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('lecture_title', sa.String(length=200), nullable=False),
    sa.Column('topic_title', sa.String(length=200), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_materials_course_id', 'materials', ['course_id'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('source_node_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_id', 'target_node_id', 'relation_type', name='uq_knowledge_edges_relation')
    )
    op.create_index('ix_knowledge_edges_course_id', 'knowledge_edges', ['course_id'], unique=False)
    op.create_table('material_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parse_status', sa.String(length=30), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_material_pages_material_id', 'material_pages', ['material_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_node_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('content_origin', sa.String(length=30), nullable=False),
    sa.Column('user_locked', sa.Boolean(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_node_id')
    )
    op.create_index('ix_notes_course_id', 'notes', ['course_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('web_search_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_jobs_material_id', 'processing_jobs', ['material_id'], unique=False)
    op.create_table('web_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=True),
    sa.Column('knowledge_node_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('search_query', sa.String(length=1000), nullable=False),
    sa.Column('score', sa.Double(), nullable=True),
    sa.Column('published_at', sa.String(length=100), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_web_sources_course_id', 'web_sources', ['course_id'], unique=False)
    op.create_table('note_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('content_origin', sa.String(length=30), nullable=False),
    sa.Column('user_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_note_revisions_note_id', 'note_revisions', ['note_id'], unique=False)
    op.create_table('page_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('font_size', sa.Double(), nullable=True),
    sa.Column('is_bold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['material_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('page_block_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_block_id'], ['page_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_block_id')
    )
    op.create_index('ix_retrieval_chunks_course_id', 'retrieval_chunks', ['course_id'], unique=False)
    op.create_table('source_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_block_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_block_id'], ['page_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_node_source_refs',
    sa.Column('knowledge_node_id', sa.String(length=36), nullable=False),
    sa.Column('source_ref_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_ref_id'], ['source_refs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_node_id', 'source_ref_id')
    )
    op.create_table('note_source_refs',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('source_ref_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_ref_id'], ['source_refs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'source_ref_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_source_refs')
    op.drop_table('knowledge_node_source_refs')
    op.drop_table('source_refs')
    op.drop_index('ix_retrieval_chunks_course_id', table_name='retrieval_chunks')
    op.drop_table('retrieval_chunks')
    op.drop_table('page_blocks')
    op.drop_index('ix_note_revisions_note_id', table_name='note_revisions')
    op.drop_table('note_revisions')
    op.drop_index('ix_web_sources_course_id', table_name='web_sources')
    op.drop_table('web_sources')
    op.drop_index('ix_processing_jobs_material_id', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_notes_course_id', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_material_pages_material_id', table_name='material_pages')
    op.drop_table('material_pages')
    op.drop_index('ix_knowledge_edges_course_id', table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index('ix_materials_course_id', table_name='materials')
    op.drop_table('materials')
    op.drop_index('ix_knowledge_nodes_course_id', table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_table('courses')
    # ### end Alembic commands ###
