"""phase one safety and jobs

Revision ID: a06cd2d44ded
Revises: 964d70a06320
Create Date: 2026-10-06 14:54:00.380899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06cd2d44ded'
down_revision: Union[str, Sequence[str], None] = '964d70a06320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('materials', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('materials', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('processing_jobs', sa.Column('error_code', sa.String(length=60), nullable=True))
    op.add_column('processing_jobs', sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('processing_jobs', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.add_column('processing_jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('processing_jobs', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.add_column('processing_jobs', sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
    # Historical retries may have left multiple active rows for one material.
    # Keep the newest and make older rows explicitly retryable before adding the index.
    op.execute(sa.text("""
        UPDATE processing_jobs SET status='failed', phase='failed',
            error_code='legacy_duplicate', error_message='Superseded by a newer job'
        WHERE status IN ('pending','processing') AND id NOT IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY material_id ORDER BY created_at DESC, id DESC
                ) AS rank FROM processing_jobs
                WHERE status IN ('pending','processing')
            ) WHERE rank=1
        )
    """))
    op.create_index('uq_processing_jobs_active_material', 'processing_jobs', ['material_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'processing')"))
    op.create_index('uq_processing_jobs_idempotency_key', 'processing_jobs', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_processing_jobs_idempotency_key', table_name='processing_jobs')
    op.drop_index('uq_processing_jobs_active_material', table_name='processing_jobs', sqlite_where=sa.text("status IN ('pending', 'processing')"))
    op.drop_column('processing_jobs', 'heartbeat_at')
    op.drop_column('processing_jobs', 'finished_at')
    op.drop_column('processing_jobs', 'started_at')
    op.drop_column('processing_jobs', 'idempotency_key')
    op.drop_column('processing_jobs', 'attempt_count')
    op.drop_column('processing_jobs', 'error_code')
    op.drop_column('materials', 'deleted_at')
    op.drop_column('materials', 'content_hash')
    op.drop_column('courses', 'deleted_at')
    # ### end Alembic commands ###
